; Script generated by the Inno Setup Script Wizard. Further Customized by Passion-Lab.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PONG Game"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Passion-Lab, Inc."
#define MyAppURL "https://www.passion-lab.github.io/"
#define MyAppExeName "Pong.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{484160E1-5BA0-41E2-B295-3164386587BE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Passion-Lab\PONG Game
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName=PONG Game
AllowNoIcons=yes
LicenseFile=D:\Passion-Lab\Python\Pong-Game\dist-Windows\LICENSE
InfoBeforeFile=D:\Passion-Lab\Python\Pong-Game\dist-Windows\README.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only).
; PrivilegesRequired=lowest
; Uncomment the follwing line to let the user choose which menthod to use while installing (user/no-privilege or alluser/privilege)
; PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\Passion-Lab\Python\Pong-Game\dist-Windows
OutputBaseFilename=PONG-Game-1.0.0-setup
SetupIconFile=icon_install.ico
SolidCompression=yes
WizardStyle=modern
DisableWelcomePage=no
WizardSmallImageFile=logo.bmp
WizardImageFile=banner.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Includes options for creating Desktop and Taskbar icons (use "; Flags: unchecked" for unchecked by default)
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Registry]
Root: HKA; Subkey: "Software\{#MyAppPublisher}"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "Installed"; ValueData: "1"
Root: HKA; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"
Root: HKA; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "CurrentVersion"; ValueData: "{#MyAppVersion}"

[UninstallDelete]
; Ensures deletion of all leftover files and folders matches with the app name upon uninstallation
Type: filesandordirs; Name: "{app}"

[Files]
Source: "D:\Passion-Lab\Python\Pong-Game\dist-Windows\Pong-Windows_v1.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Passion-Lab\Python\Pong-Game\dist-Windows\Pong-Windows_v1.0\_internal\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
; Source: "D:\Passion-Lab\Python\Pong-Game\dist-Windows\Pong-Windows_v1.0\_internal\README.md"; DestDir: "{app}"; Flags: ignoreversion
; Source: "D:\Passion-Lab\Python\Pong-Game\dist-Windows\Pong-Windows_v1.0\_internal\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
; Creates Start Menu shortcuts
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; IconFilename: "{app}\icon_uninstall.ico"
; Creates Desktop shortcut
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
; Creates Quick Launch (Taskbar) shortcut. Use "{userappdata}" option for CurrentUserOnly mode, else "{commonappdata}" for AllUser installation mode
; Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon
Name: "{commonappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

